cc_library(
    name = "common_types",
    hdrs = ["error_code.h"],
    visibility = ["@core//:__pkg__"],
)

cc_library(
    name = "common_converter",
    hdrs = ["endianess_converter.h"],
    visibility = ["@core//:__pkg__"],
)